import React from "react";
import { Episode } from "../modules/rickmortyapi";
import EpisodeItem from "./EpisodeItem";
import Head from "next/head";
import PageHeader from "./PageHeader";
import { Container, Grid, Paper } from "@mui/material";
import EpisodeList from "./EpisodeList";
import { useTranslation } from "next-i18next";

interface PageLayoutProps {
  title: string;
}

const PageLayout = ({
  title,
  children,
}: React.PropsWithChildren<PageLayoutProps>) => {
  return (
    <React.Fragment>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageHeader title={title} />
      <Container>{children}</Container>
    </React.Fragment>
  );
};

export default PageLayout;
