import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { Box, Container, List, ListItem, Paper } from "@mui/material";
import Link from "../components/Link";
import { useTranslation } from "next-i18next";
import PageHeader from "../components/PageHeader";

const Home: NextPage = () => {
  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>

      <Container
        sx={{ alignContent: "center", justifyContent: "center" }}
        maxWidth="md"
      >
        <Box
          sx={{
            width: "100%",
            maxWidth: 360,
            bgcolor: "background.paper",
          }}
        >
          <List>
            <ListItem>
              <Link href="/blog/rest">Blog (rest</Link>
            </ListItem>
          </List>
        </Box>
      </Container>
    </React.Fragment>
  );
};

export default Home;
